version: "3"

services:
  app_proxy:
    environment:
      APP_HOST: lily-wallet_1
      APP_PORT: 42069
      PROXY_AUTH_ADD: "false"

  lily-wallet:
    image: kaybesee/lily-wallet:latest
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - /dev/bus:/dev/bus:ro
      - /run/udev:/run/udev:ro
    environment:
      - EXPRESS_PORT=8080
      - ELECTRUM_IP=$ELECTRUM_IP
      - ELECTRUM_PORT=$ELECTRUM_PORT
      - APP_PASSWORD=$APP_PASSWORD
      - APP_DATA_DIR=${APP_DATA_DIR}
      - LND_IP=$LND_IP
      - LND_GRPC_PORT=$LND_GRPC_PORT
      - LND_WALLET_NAME='Umbrel'
    devices:
      - /dev/bus/usb
    ports:
      - "42069:8080"
    device_cgroup_rules:
      - "c 189:* rmw"
